# Generated by Django 5.0 on 2025-07-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Depth level in the tree hierarchy')),
                ('lft', models.IntegerField(db_column='ileft', help_text='Left boundary for nested set')),
                ('rgt', models.IntegerField(db_column='iright', help_text='Right boundary for nested set')),
            ],
            options={
                'db_table': 'node_tree',
                'ordering': ['lft'],
            },
        ),
        migrations.CreateModel(
            name='NodeTreeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Italian', 'Italian')], help_text='Language of the translation', max_length=50)),
                ('node_name', models.CharField(help_text='Translated name of the node', max_length=255)),
                ('node', models.ForeignKey(help_text='Reference to the node', on_delete=django.db.models.deletion.CASCADE, related_name='names', to='org_chart.nodetree')),
            ],
            options={
                'db_table': 'node_tree_names',
                'unique_together': {('node', 'language')},
            },
        ),
    ]
